name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  push_to_Docker_Hub:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: 'Create env file'
          run: |
            touch .env
            echo SECRET_SSH_PASSWORD=${{ secrets.SSH_PASSWORD }} >> .env
            cat .env
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/naturodashboard:latest
