name: Node.js CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Load Environment Variables
      env:
        SECRET_SSH_PASSWORD: ${{ secrets.SECRET_SSH_PASSWORD }}
    - run: npm i
    - run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/NaturoDashboard/Website
          git stash
          git stash drop
          git pull
          git status
          npm install --only=prod
          npm install vite
          npm run build
          pm2 restart 0
